crawl
xu1jia2qi3/argus pull request #6
Opened 2019-12-05 01:34 UTC by xu1jia2qi3

2019-12-05 01:35 UTC, xu1jia2qi3 commented
add crawler

2019-12-05 01:51 UTC, tiddler requested changes
Please fix some issues.

2019-12-05 01:51 UTC, tiddler commented on crawl.py
> +                # print(f'Download complete - {img_id}.jpg')
We can keep the `print` as log.

2019-12-05 01:51 UTC, tiddler commented on crawl.py
> +    sem = asyncio.Semaphore(10)
Change the number `10` here as a config variable, like `MAX_DOWNLOAD_NUMBER`.

2019-12-05 01:51 UTC, tiddler commented on crawl.py
> +        with open('./camera.json', 'r') as f:
Same, change the path to a config variable, like `CAMERA_DATA_PATH`.

2019-12-05 15:17 UTC, tiddler commented
Also, create a folder, like `src` to place all code files.

2019-12-17 19:32 UTC, tiddler commented
@xu1jia2qi3 Any updates

2019-12-19 15:59 UTC, xu1jia2qi3 commented
fixed code

2019-12-19 16:06 UTC, tiddler requested changes
Remove jpg files?

2019-12-19 16:06 UTC, tiddler commented on .vscode/settings.json
> +    "python.pythonPath": "C:\\Users\\DD\\AppData\\Local\\Programs\\Python\\Python36\\python.exe"
Unnecessary file.

2019-12-19 16:06 UTC, tiddler commented on .gitignore
> +*.docx
Add `.vscode/` as well.

2019-12-19 16:06 UTC, tiddler commented on crawl.py
>                  # print(f'Download complete - {img_id}.jpg')
Uncomment this line.

2019-12-19 16:55 UTC, tiddler requested changes

2019-12-19 16:55 UTC, tiddler commented on .gitignore
> +.Snapshot/
Change `.Snapshot` to `Snapshot`

2019-12-19 19:34 UTC, tiddler approved these changes
Good Job.

2019-12-19 19:35 UTC, merged